#!/usr/bin/env bash
# TealKit Server - one-command installer
# Usage: bash install-server.sh [path/to/tealkit_server_<version>.tar.gz] [--api-key YOUR_KEY]
#
# The API key is generated by the TealKit app (Settings -> Server Mode).
# Copy it from the app and pass it here with --api-key, or enter it when prompted.
#
# Steps:
#   1. Check Docker >= 24 and Compose V2 are installed
#   2. Unzip and load the image archive into Docker
#   3. Accept (or prompt for) the API key that the app generated
#   4. Write docker-compose.yml and .env into ~/tealkit-server/
#   5. Start the container
#   6. Verify the health endpoint

set -euo pipefail

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

ok()   { echo -e "${GREEN}[OK]${NC}  $*"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
fail() { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

echo ""
echo "  TealKit Server Installer"
echo "  ========================"
echo ""

# ---------------------------------------------------------------------------
# 1. Check Docker
# ---------------------------------------------------------------------------
if ! command -v docker &>/dev/null; then
  fail "Docker not found. Install Docker Engine 24+ from https://docs.docker.com/engine/install/"
fi

DOCKER_VERSION=$(docker version --format '{{.Server.Version}}' 2>/dev/null || echo "0.0.0")
DOCKER_MAJOR=$(echo "$DOCKER_VERSION" | cut -d. -f1)
if [ "$DOCKER_MAJOR" -lt 24 ]; then
  fail "Docker Engine 24+ required (found $DOCKER_VERSION). Upgrade: https://docs.docker.com/engine/install/"
fi
ok "Docker $DOCKER_VERSION"

if ! docker compose version &>/dev/null; then
  fail "Docker Compose V2 not found. It is bundled with Docker Engine 24+."
fi
COMPOSE_VERSION=$(docker compose version --short 2>/dev/null || echo "unknown")
ok "Docker Compose $COMPOSE_VERSION"

# ---------------------------------------------------------------------------
# 2. Find the archive
# ---------------------------------------------------------------------------
IMAGE_NAME="ghcr.io/lschaffer/tealkit-server:latest"

# Parse arguments: positional archive path and optional --api-key flag
ARCHIVE=""
API_KEY_ARG=""
PREV=""
for arg in "$@"; do
  if [ "$PREV" = "--api-key" ]; then
    API_KEY_ARG="$arg"
  elif [ "$arg" = "--api-key" ]; then
    : # handled on next iteration
  elif [ -z "$ARCHIVE" ] && [[ "$arg" != --* ]]; then
    ARCHIVE="$arg"
  fi
  PREV="$arg"
done

if [ -z "$ARCHIVE" ]; then
  ARCHIVE=$(ls tealkit_server_*.tar.gz 2>/dev/null | sort -V | tail -1 || true)
fi

if [ -z "$ARCHIVE" ] || [ ! -f "$ARCHIVE" ]; then
  fail "Image archive not found. Usage: bash install-server.sh tealkit_server_<version>.tar.gz"
fi

echo "  Archive : $ARCHIVE"

# ---------------------------------------------------------------------------
# 3. Unzip and load into Docker
# ---------------------------------------------------------------------------
echo "  Unzipping..."
TAR_FILE="${ARCHIVE%.gz}"

if [ "$ARCHIVE" != "$TAR_FILE" ]; then
  gunzip -k -f "$ARCHIVE"
  ok "Unzipped to $TAR_FILE"
else
  TAR_FILE="$ARCHIVE"
fi

echo "  Loading image into Docker..."
docker load < "$TAR_FILE"
ok "Image loaded"

# Remove the unzipped .tar (keep the original .tar.gz)
if [ "$ARCHIVE" != "$TAR_FILE" ]; then
  rm -f "$TAR_FILE"
fi

# ---------------------------------------------------------------------------
# 4. Get API key from the TealKit app
# ---------------------------------------------------------------------------
INSTALL_DIR="$HOME/tealkit-server"
ENV_FILE="$INSTALL_DIR/.env"

mkdir -p "$INSTALL_DIR/data"

API_KEY=""

# Check for existing key first (reinstall scenario)
if [ -f "$ENV_FILE" ]; then
  EXISTING_KEY=$(grep -E '^TEALKIT_API_KEY=' "$ENV_FILE" | cut -d= -f2 || true)
  if [ -n "$EXISTING_KEY" ]; then
    API_KEY="$EXISTING_KEY"
    warn "Existing API key found - reusing it (app will still connect without changes)"
  fi
fi

# Use key from --api-key argument if provided
if [ -n "$API_KEY_ARG" ]; then
  API_KEY="$API_KEY_ARG"
  ok "Using API key from argument"
fi

# Prompt interactively if still no key
if [ -z "$API_KEY" ]; then
  echo ""
  echo "  The TealKit app auto-generates a unique API key."
  echo "  To find it: open the app -> Settings -> Server Mode"
  echo "  The key is shown in the 'Server API Key' section (tap the copy icon)."
  echo ""
  read -rp "  Paste your API key here: " API_KEY
  echo ""
  if [ -z "$API_KEY" ]; then
    fail "API key is required. Get it from the TealKit app."
  fi
  ok "API key accepted"
fi

# ---------------------------------------------------------------------------
# 5. Write config files
# ---------------------------------------------------------------------------
cat > "$ENV_FILE" <<EOF
TEALKIT_API_KEY=${API_KEY}
TEALKIT_PORT=7771
TEALKIT_HOST=0.0.0.0
TEALKIT_DATA_DIR=/data
EOF
chmod 600 "$ENV_FILE"

cat > "$INSTALL_DIR/docker-compose.yml" <<EOF
services:
  tealkit_server:
    image: ${IMAGE_NAME}
    container_name: tealkit_server
    restart: unless-stopped
    ports:
      - "7771:7771"
    volumes:
      - ./data:/data
    env_file: .env
    healthcheck:
      test: ["/usr/bin/wget", "-qO-", "http://localhost:7771/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
EOF

ok "Config written to $INSTALL_DIR/"

# ---------------------------------------------------------------------------
# 6. Start the container
# ---------------------------------------------------------------------------
cd "$INSTALL_DIR"
docker compose up -d
ok "Container started"

# ---------------------------------------------------------------------------
# 7. Health check
# ---------------------------------------------------------------------------
echo "  Waiting for server to be ready..."
HEALTHY=0
for i in $(seq 1 15); do
  if curl -sf "http://localhost:7771/health" &>/dev/null; then
    ok "Server is healthy"
    HEALTHY=1
    break
  fi
  sleep 2
done

if [ "$HEALTHY" -eq 0 ]; then
  warn "Health check did not pass within 30s. Check logs: docker logs tealkit_server"
fi

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
SERVER_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "localhost")

echo ""
echo "  -----------------------------------------------"
echo "  TealKit Server is running!"
echo "  -----------------------------------------------"
echo "  Server URL : http://${SERVER_IP}:7771"
  echo "  -----------------------------------------------"
  echo "  In the TealKit app:"
  echo "  Settings -> Server Mode -> enter the Server URL above"
  echo "  The app already holds your API key - no need to re-enter it."
echo "  -----------------------------------------------"
echo ""
echo "  Logs  : docker logs -f tealkit_server"
echo "  Stop  : cd $INSTALL_DIR && docker compose down"
echo "  Start : cd $INSTALL_DIR && docker compose up -d"
echo "  Data  : $INSTALL_DIR/data/"
echo ""
