import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../l10n/app_localizations.dart';
import 'package:uuid/uuid.dart';

import '../config/app_theme.dart';
import '../models/mcp_models.dart';
import '../providers/active_task_provider.dart';
import '../providers/llm_settings_provider.dart';
import '../providers/server_mode_provider.dart';
import '../services/app_logger.dart';
import '../services/data_sources_settings_service.dart';

import '../services/llm_service.dart';

import '../mcp/servers/ssh_mcp_server.dart';
import '../services/shell_script_service.dart';
import '../services/task_runner_service.dart';
import '../widgets/code_editor_field.dart';

// ═══════════════════════════════════════════════════════════════
// Script Library Screen
// ═══════════════════════════════════════════════════════════════

/// Full-screen view for managing the global shell script library.
///
/// Scripts can be created, edited, deleted, and generated by the LLM.
/// Each script is persisted via [ScriptLibraryService].
class ScriptLibraryScreen extends ConsumerStatefulWidget {
  const ScriptLibraryScreen({super.key, this.onInsertScriptPrompt});

  final void Function(String scriptName)? onInsertScriptPrompt;

  /// Push the screen and return [true] if any changes were made.
  static Future<bool?> show(BuildContext context, {void Function(String scriptName)? onInsertScriptPrompt}) {
    return Navigator.of(context).push<bool>(
      MaterialPageRoute(fullscreenDialog: true, builder: (_) => ScriptLibraryScreen(onInsertScriptPrompt: onInsertScriptPrompt)),
    );
  }

  @override
  ConsumerState<ScriptLibraryScreen> createState() => _ScriptLibraryScreenState();
}

class _ScriptLibraryScreenState extends ConsumerState<ScriptLibraryScreen> {
  bool _loading = true;
  List<ShellScript> _scripts = [];
  bool _changed = false;

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    final client = (ref.read(serverModeProvider).value?.isRemote ?? false)
        ? ref.read(serverApiClientProvider)
        : null;
    await ScriptLibraryService.instance.load(client);
    if (!mounted) return;
    setState(() {
      _scripts = List.from(ScriptLibraryService.instance.scripts);
      _loading = false;
    });
  }

  void _refresh() {
    setState(() {
      _scripts = List.from(ScriptLibraryService.instance.scripts);
      _changed = true;
    });
  }

  Future<void> _loadSamples() async {
    final svc = ScriptLibraryService.instance;
    final samples = [
      (
        name: 'Disk Usage',
        description: 'Shows disk usage for all mounted filesystems (df -h) sorted by use%.',
        content:
            '#!/bin/bash\n'
            '# Disk usage — all mounted filesystems sorted by use%\n'
            'df -h --output=source,size,used,avail,pcent,target 2>/dev/null | '
            '(read header; echo "\$header"; sort -rk5 -t\' \') || df -h\n',
      ),
      (
        name: 'Biggest Files in /usr/lib',
        description: 'Lists the 20 largest files under /usr/lib, sorted by size descending.',
        content:
            '#!/bin/bash\n'
            '# 20 biggest files in /usr/lib\n'
            'find /usr/lib -maxdepth 5 -type f -printf "%s\\t%p\\n" 2>/dev/null | '
            'sort -rn | head -20 | '
            'awk \'{printf "%-10s %s\\n", (\$1>1073741824 ? sprintf("%.1fG",\$1/1073741824) : \$1>1048576 ? sprintf("%.1fM",\$1/1048576) : sprintf("%.0fK",\$1/1024)), \$2}\'\n',
      ),
      (
        name: 'Top 10 Processes',
        description: 'Shows the 10 processes consuming the most CPU, with user, PID, CPU%, MEM% and command.',
        content:
            '#!/bin/bash\n'
            '# Top 10 processes by CPU usage\n'
            'ps aux --sort=-%cpu 2>/dev/null | head -11 || ps aux | head -11\n',
      ),
    ];

    final existingNames = _scripts.map((s) => s.name).toSet();
    int added = 0;
    final client = (ref.read(serverModeProvider).value?.isRemote ?? false)
        ? ref.read(serverApiClientProvider)
        : null;
    for (final s in samples) {
      if (existingNames.contains(s.name)) continue;
      await svc.addScript(name: s.name, description: s.description, content: s.content, client: client);
      added++;
    }
    _refresh();
    if (mounted) {
      final msg = added == 0 ? 'All sample scripts already exist.' : '$added sample script${added == 1 ? '' : 's'} added.';
      ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(msg), behavior: SnackBarBehavior.floating));
    }
  }

  Future<void> _openEditor({ShellScript? existing}) async {
    final result = await _ScriptEditorDialog.show(context, ref: ref, existing: existing, onInsertScriptPrompt: widget.onInsertScriptPrompt);
    if (result == true) _refresh();
  }

  Future<void> _deleteScript(ShellScript script) async {
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (ctx) => AlertDialog(
        title: Text(L.of(context).deleteScriptTitle),
        content: Text(L.of(context).deleteScriptConfirm(script.name)),
        actions: [
          TextButton(onPressed: () => Navigator.pop(ctx, false), child: Text(L.of(context).cancel)),
          TextButton(
            onPressed: () => Navigator.pop(ctx, true),
            child: Text(L.of(context).delete, style: TextStyle(color: AppTheme.error)),
          ),
        ],
      ),
    );
    if (confirmed != true) return;
    final client = (ref.read(serverModeProvider).value?.isRemote ?? false)
        ? ref.read(serverApiClientProvider)
        : null;
    await ScriptLibraryService.instance.deleteScript(script.id, client);
    _refresh();
    if (mounted) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text(L.of(context).scriptDeletedMsg(script.name)), behavior: SnackBarBehavior.floating));
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Scaffold(
      appBar: AppBar(
        title: Text(L.of(context).shellScriptLibraryTitle),
        leading: IconButton(icon: const Icon(Icons.close), onPressed: () => Navigator.of(context).pop(_changed)),
        actions: [
          IconButton(icon: const Icon(Icons.science_outlined), tooltip: 'Load sample scripts', onPressed: _loadSamples),
          IconButton(icon: const Icon(Icons.add), tooltip: L.of(context).newScriptTooltip, onPressed: () => _openEditor()),
        ],
      ),
      body: _loading
          ? const Center(child: CircularProgressIndicator())
          : _scripts.isEmpty
          ? Center(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Icon(Icons.terminal, size: 64, color: Colors.grey[400]),
                  const SizedBox(height: 16),
                  Text(L.of(context).noScriptsYet, style: theme.textTheme.titleMedium?.copyWith(color: Colors.grey[500])),
                  const SizedBox(height: 8),
                  Text(L.of(context).createFirstScriptHint, style: theme.textTheme.bodySmall?.copyWith(color: Colors.grey[400])),
                  const SizedBox(height: 24),
                  FilledButton.icon(
                    onPressed: () => _openEditor(),
                    icon: const Icon(Icons.add),
                    label: Text(L.of(context).createScriptButton),
                  ),
                  const SizedBox(height: 12),
                  OutlinedButton.icon(
                    onPressed: _loadSamples,
                    icon: const Icon(Icons.science_outlined, size: 18),
                    label: const Text('Load sample scripts'),
                  ),
                ],
              ),
            )
          : ListView.separated(
              padding: const EdgeInsets.symmetric(vertical: 8),
              itemCount: _scripts.length,
              separatorBuilder: (context, idx) => const Divider(height: 1, indent: 72),
              itemBuilder: (ctx, i) {
                final s = _scripts[i];
                return ListTile(
                  leading: CircleAvatar(
                    backgroundColor: AppTheme.primaryBlue.withValues(alpha: 0.12),
                    child: const Icon(Icons.terminal, color: AppTheme.primaryBlue, size: 20),
                  ),
                  title: Text(s.name, style: const TextStyle(fontWeight: FontWeight.w600)),
                  subtitle: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      if (s.description.isNotEmpty)
                        Text(s.description, maxLines: 1, overflow: TextOverflow.ellipsis)
                      else
                        Text('${'\n'.allMatches(s.content).length + 1} lines', style: TextStyle(color: Colors.grey[500], fontSize: 12)),
                      const SizedBox(height: 2),
                      Text(
                        'Mode: ${s.runLocally ? 'Local' : 'SSH'}',
                        style: TextStyle(
                          color: s.runLocally ? AppTheme.success : Colors.grey[500],
                          fontSize: 11,
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                    ],
                  ),
                  trailing: Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      IconButton(
                        icon: const Icon(Icons.edit_outlined),
                        tooltip: L.of(context).editScriptTooltip,
                        onPressed: () => _openEditor(existing: s),
                      ),
                      IconButton(
                        icon: Icon(Icons.delete_outline, color: AppTheme.error),
                        tooltip: L.of(context).deleteScriptTooltip,
                        onPressed: () => _deleteScript(s),
                      ),
                    ],
                  ),
                  onTap: () => _openEditor(existing: s),
                );
              },
            ),
    );
  }
}

// ═══════════════════════════════════════════════════════════════
// Script Editor Dialog
// ═══════════════════════════════════════════════════════════════

class _ScriptEditorDialog extends ConsumerStatefulWidget {
  const _ScriptEditorDialog({this.existing, this.onInsertScriptPrompt});

  final ShellScript? existing;
  final void Function(String scriptName)? onInsertScriptPrompt;

  static Future<bool?> show(
    BuildContext context, {
    required WidgetRef ref,
    ShellScript? existing,
    void Function(String scriptName)? onInsertScriptPrompt,
  }) {
    return showDialog<bool>(
      context: context,
      barrierDismissible: false,
      builder: (_) => _ScriptEditorDialog(existing: existing, onInsertScriptPrompt: onInsertScriptPrompt),
    );
  }

  @override
  ConsumerState<_ScriptEditorDialog> createState() => _ScriptEditorDialogState();
}

class _ScriptEditorDialogState extends ConsumerState<_ScriptEditorDialog> {
  static const String _defaultGenerationSystemPrompt =
      'You are an expert Linux shell scripting assistant. '
      'Generate clean, production-quality bash/sh scripts with correct syntax. '
      'Validate the script mentally before output. '
      'Output only the script code, no preamble or explanation.';

  late final TextEditingController _nameCtrl;
  late final TextEditingController _descCtrl;
  late final TextEditingController _contentCtrl;
  late final TextEditingController _generatePromptCtrl;
  late final TextEditingController _systemPromptCtrl;

  bool _saving = false;
  bool _generating = false;
  bool _testing = false;
  bool _includeComments = true;
  // 'llm1' = global LLM 1, 'llm2' = global LLM 2
  String _codeLlmChoice = 'llm1';

  String _sshHost = '';
  int _sshPort = 22;
  String _sshUsername = '';
  String _sshPassword = '';
  int _timeoutSeconds = 120;
  bool _runLocally = false;
  late TextEditingController _timeoutCtrl;

  bool get _hasLocalSshConfig => _sshHost.isNotEmpty && _sshUsername.isNotEmpty;
  bool get _hasSshForTest => _hasLocalSshConfig || DataSourcesSettingsService.instance.isSshConfigured;
  bool get _canUseLocalShellMode => (Platform.isLinux || Platform.isMacOS) && !(ref.read(serverModeProvider).value?.isRemote ?? false);
  bool get _canTestRun => _runLocally ? (Platform.isLinux || Platform.isMacOS) : _hasSshForTest;

  Widget _buildCommentsToggle(ThemeData theme) {
    return Row(
      mainAxisSize: MainAxisSize.min,
      children: [
        Text(L.of(context).withCommentsLabel, style: theme.textTheme.bodySmall?.copyWith(color: theme.colorScheme.onSurfaceVariant)),
        Switch(
          value: _includeComments,
          onChanged: (value) => setState(() => _includeComments = value),
          materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
        ),
      ],
    );
  }

  @override
  void initState() {
    super.initState();
    final s = widget.existing;
    _nameCtrl = TextEditingController(text: s?.name ?? '');
    _descCtrl = TextEditingController(text: s?.description ?? '');
    _contentCtrl = TextEditingController(text: s?.content ?? '');
    _generatePromptCtrl = TextEditingController(text: s?.generationPrompt ?? '');
    _systemPromptCtrl = TextEditingController(text: s?.generationSystemPrompt ?? _defaultGenerationSystemPrompt);
    _sshHost = s?.sshHost ?? '';
    _sshPort = s?.sshPort ?? 22;
    _sshUsername = s?.sshUsername ?? '';
    _sshPassword = s?.sshPassword ?? '';
    _timeoutSeconds = s?.timeoutSeconds ?? 120;
    _runLocally = (s?.runLocally ?? false) && _canUseLocalShellMode;
    _timeoutCtrl = TextEditingController(text: _timeoutSeconds.toString());
  }

  @override
  void dispose() {
    _nameCtrl.dispose();
    _descCtrl.dispose();
    _contentCtrl.dispose();
    _generatePromptCtrl.dispose();
    _systemPromptCtrl.dispose();
    _timeoutCtrl.dispose();
    super.dispose();
  }

  Future<void> _save() async {
    final name = _nameCtrl.text.trim();
    if (name.isEmpty) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text(L.of(context).scriptNameRequiredMsg), backgroundColor: Colors.orange));
      return;
    }
    setState(() => _saving = true);
    try {
      final svc = ScriptLibraryService.instance;
      final genPrompt = _generatePromptCtrl.text.trim();
      final client = (ref.read(serverModeProvider).value?.isRemote ?? false)
          ? ref.read(serverApiClientProvider)
          : null;
      if (widget.existing != null) {
        final updated = widget.existing!.copyWith(
          name: name,
          description: _descCtrl.text.trim(),
          content: _contentCtrl.text,
          generationSystemPrompt: _systemPromptCtrl.text.trim(),
          generationPrompt: genPrompt.isNotEmpty ? genPrompt : null,
          sshHost: _sshHost,
          sshPort: _sshPort,
          sshUsername: _sshUsername,
          sshPassword: _sshPassword,
          timeoutSeconds: _timeoutSeconds,
          runLocally: _runLocally,
        );
        await svc.updateScript(updated, client);
      } else {
        await svc.addScript(
          name: name,
          description: _descCtrl.text.trim(),
          content: _contentCtrl.text,
          generationSystemPrompt: _systemPromptCtrl.text.trim(),
          generationPrompt: genPrompt,
          sshHost: _sshHost,
          sshPort: _sshPort,
          sshUsername: _sshUsername,
          sshPassword: _sshPassword,
          timeoutSeconds: _timeoutSeconds,
          runLocally: _runLocally,
          client: client,
        );
      }
      if (mounted) Navigator.of(context).pop(true);
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text(L.of(context).scriptSaveFailed(e.toString())), backgroundColor: AppTheme.error));
      }
    } finally {
      if (mounted) setState(() => _saving = false);
    }
  }

  Future<void> _generateScript() async {
    final prompt = _generatePromptCtrl.text.trim();
    if (prompt.isEmpty) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text(L.of(context).describeForGeneration), backgroundColor: Colors.orange));
      return;
    }

    final llmSettings = ref.read(llmSettingsProvider);
    LLMService? effectiveLlm;

    if (_codeLlmChoice == 'llm2' && llmSettings.isConfigured2) {
      // Use LLM 2 (coding)
      final llm2 = LLMService();
      await TaskRunnerService.configureLlmFromParams(
        llmService: llm2,
        providerKey: llmSettings.provider2.configKey,
        model: llmSettings.model2,
        apiKey: llmSettings.apiKey2,
        baseUrl: llmSettings.baseUrl2,
      );
      if (llm2.isConfigured) effectiveLlm = llm2;
    }

    // Fallback: LLM 1 → LLM 2
    if (effectiveLlm == null) {
      if (llmSettings.isConfigured) {
        final fallback = LLMService();
        await fallback.loadSavedProviderAndModel();
        if (fallback.isConfigured) effectiveLlm = fallback;
      } else if (llmSettings.isConfigured2) {
        final llm2 = LLMService();
        await TaskRunnerService.configureLlmFromParams(
          llmService: llm2,
          providerKey: llmSettings.provider2.configKey,
          model: llmSettings.model2,
          apiKey: llmSettings.apiKey2,
          baseUrl: llmSettings.baseUrl2,
        );
        if (llm2.isConfigured) effectiveLlm = llm2;
      }
    }

    if (effectiveLlm == null) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(L.of(context).noLlmForScript), backgroundColor: Colors.orange));
      return;
    }

    setState(() => _generating = true);
    try {
      final rules = <String>[
        'Output ONLY the bash script, starting with #!/bin/bash',
        if (_includeComments) 'Add brief inline comments for each major step',
        if (!_includeComments) 'Do NOT include comments in the script',
        'Handle errors with set -e and appropriate error messages',
        'Do NOT include any explanation outside the script itself',
        'Do NOT wrap the output in markdown code fences',
      ];

      final metaPrompt =
          '''Generate a Linux/Unix bash shell script that does the following:

$prompt

Rules:
- ${rules.join('\n- ')}''';

      final baseSystemPrompt = _systemPromptCtrl.text.trim().isNotEmpty ? _systemPromptCtrl.text.trim() : _defaultGenerationSystemPrompt;
      final systemPrompt = StringBuffer(baseSystemPrompt);
      if (!_includeComments) {
        systemPrompt.write(' Do not include comments.');
      }

      final response = await effectiveLlm.generateChatCompletion(
        messages: [
          ChatMessage(id: const Uuid().v4(), role: ChatRole.system, content: systemPrompt.toString(), timestamp: DateTime.now()),
          ChatMessage(id: const Uuid().v4(), role: ChatRole.user, content: metaPrompt, timestamp: DateTime.now()),
        ],
        maxTokens: 1024,
      );

      var script = response.content.trim();

      // Strip markdown code fences if model added them anyway.
      if (script.startsWith('```')) {
        final lines = script.split('\n');
        script = lines.skip(1).where((l) => !l.startsWith('```')).join('\n').trim();
      }

      if (mounted) {
        setState(() => _contentCtrl.text = script);

        // Auto-fill name if empty.
        if (_nameCtrl.text.isEmpty) {
          final firstLine = prompt.split('\n').first;
          final name = firstLine.length > 40 ? '${firstLine.substring(0, 37)}...' : firstLine;
          _nameCtrl.text = name;
          _descCtrl.text = prompt.length > 120 ? '${prompt.substring(0, 117)}...' : prompt;
        }
      }
    } catch (e) {
      log.error('[ScriptLibrary] LLM generation failed: $e');
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text(L.of(context).scriptGenerationFailed(e.toString())), backgroundColor: AppTheme.error));
      }
    } finally {
      if (mounted) setState(() => _generating = false);
    }
  }

  Future<void> _testRun() async {
    final scriptName = _nameCtrl.text.trim();
    final content = _contentCtrl.text.trim();
    if (content.isEmpty) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(const SnackBar(content: Text('No script content to test.'), backgroundColor: Colors.orange));
      return;
    }

    if (!_runLocally && !_hasSshForTest) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('SSH not configured. Tap the Server button to set connection details.'),
          backgroundColor: Colors.orange,
        ),
      );
      return;
    }

    final argsCtrl = TextEditingController();
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (ctx) => AlertDialog(
        title: Text('Test Run${scriptName.isNotEmpty ? ': $scriptName' : ''}'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Parameters (optional args passed to the script):',
              style: Theme.of(ctx).textTheme.bodySmall?.copyWith(color: Theme.of(ctx).colorScheme.onSurfaceVariant),
            ),
            const SizedBox(height: 8),
            TextField(
              controller: argsCtrl,
              decoration: const InputDecoration(hintText: 'e.g. /var/log --verbose', border: OutlineInputBorder()),
              autofocus: true,
            ),
          ],
        ),
        actions: [
          TextButton(onPressed: () => Navigator.pop(ctx, false), child: const Text('Cancel')),
          FilledButton.icon(
            onPressed: () => Navigator.pop(ctx, true),
            icon: const Icon(Icons.play_arrow, size: 18),
            label: const Text('Run'),
            style: FilledButton.styleFrom(backgroundColor: AppTheme.primaryBlue),
          ),
        ],
      ),
    );
    final args = argsCtrl.text.trim();
    // Defer disposal so the dialog's pop animation can finish before the
    // controller is torn down. Disposing immediately causes the TextField's
    // cursor AnimatedWidget to call addListener on an already-disposed
    // ChangeNotifier while the route is still fading out.
    Future<void>.delayed(const Duration(milliseconds: 500), argsCtrl.dispose);
    if (confirmed != true || !mounted) return;

    setState(() => _testing = true);
    Map<String, dynamic> result;
    try {
      result = await SshMcpServer.runContentForTest(
        content,
        args: args,
        runLocally: _runLocally,
        sshHost: _sshHost,
        sshPort: _sshPort,
        sshUsername: _sshUsername,
        sshPassword: _sshPassword,
      );
    } catch (e) {
      result = {'error': e.toString()};
    } finally {
      if (mounted) setState(() => _testing = false);
    }

    if (!mounted) return;

    final isError = result.containsKey('error');
    final stdout = result['stdout'] as String? ?? '';
    final stderr = result['stderr'] as String? ?? '';
    final exitCode = result['exitCode'] as int?;
    final error = result['error'] as String?;

    await showDialog<void>(
      context: context,
      builder: (ctx) {
        final screenSize = MediaQuery.of(ctx).size;
        final isMobile = screenSize.width < 600;
        return Dialog(
          insetPadding: isMobile ? EdgeInsets.zero : const EdgeInsets.symmetric(horizontal: 24, vertical: 32),
          clipBehavior: Clip.antiAlias,
          shape: isMobile ? const RoundedRectangleBorder() : null,
          child: SizedBox(
            width: isMobile ? screenSize.width : 680,
            height: isMobile ? screenSize.height : null,
            child: SafeArea(
              child: Column(
                children: [
                  Padding(
                    padding: const EdgeInsets.fromLTRB(20, 16, 8, 0),
                    child: Row(
                      children: [
                        Icon(
                          isError ? Icons.error_outline : (exitCode == 0 ? Icons.check_circle_outline : Icons.warning_amber_outlined),
                          color: isError || (exitCode != null && exitCode != 0) ? AppTheme.error : Colors.green,
                        ),
                        const SizedBox(width: 12),
                        Expanded(
                          child: Text(
                            isError ? 'Test Run Failed' : 'Test Output (exit code: $exitCode)',
                            style: Theme.of(ctx).textTheme.titleMedium?.copyWith(fontWeight: FontWeight.w700),
                          ),
                        ),
                        IconButton(icon: const Icon(Icons.close), onPressed: () => Navigator.of(ctx).pop()),
                      ],
                    ),
                  ),
                  const Divider(height: 1),
                  Flexible(
                    child: SingleChildScrollView(
                      padding: const EdgeInsets.all(16),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          if (isError) ...[
                            Text(
                              'Error:',
                              style: TextStyle(color: AppTheme.error, fontWeight: FontWeight.bold),
                            ),
                            const SizedBox(height: 4),
                            _OutputBox(text: error ?? ''),
                          ] else ...[
                            if (stdout.isNotEmpty) ...[
                              const Text('stdout:', style: TextStyle(fontWeight: FontWeight.bold)),
                              const SizedBox(height: 4),
                              _OutputBox(text: stdout),
                              if (stderr.isNotEmpty) const SizedBox(height: 12),
                            ],
                            if (stderr.isNotEmpty) ...[
                              Text(
                                'stderr:',
                                style: TextStyle(color: AppTheme.error, fontWeight: FontWeight.bold),
                              ),
                              const SizedBox(height: 4),
                              _OutputBox(text: stderr),
                            ],
                            if (stdout.isEmpty && stderr.isEmpty) const Text('(no output)', style: TextStyle(color: Colors.grey)),
                          ],
                        ],
                      ),
                    ),
                  ),
                  const Divider(height: 1),
                  Padding(
                    padding: const EdgeInsets.all(12),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.end,
                      children: [FilledButton(onPressed: () => Navigator.of(ctx).pop(), child: const Text('Close'))],
                    ),
                  ),
                ],
              ),
            ),
          ),
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final isNew = widget.existing == null;
    final screenSize = MediaQuery.of(context).size;
    final isMobile = screenSize.width < 600;
    final taskState = ref.watch(activeTaskProvider);
    final llmSettings = ref.watch(llmSettingsProvider);
    final llmReady = taskState?.llmService?.isConfigured == true || llmSettings.isConfigured || llmSettings.isConfigured2;
    final isServerMode = ref.watch(serverModeProvider).value?.isRemote ?? false;

    final dialogBody = Column(
      mainAxisSize: isMobile ? MainAxisSize.max : MainAxisSize.min,
      children: [
        // ── Header ────────────────────────────────────────────
        Padding(
          padding: const EdgeInsets.fromLTRB(20, 16, 8, 0),
          child: Row(
            children: [
              Icon(Icons.terminal, color: AppTheme.primaryBlue),
              const SizedBox(width: 12),
              Text(
                isNew ? L.of(context).newShellScriptTitle : L.of(context).editScriptDialogTitle,
                style: theme.textTheme.titleMedium?.copyWith(fontWeight: FontWeight.w700),
              ),
              const Spacer(),
              IconButton(
                icon: Icon(Icons.dns, color: _hasLocalSshConfig ? AppTheme.success : null),
                tooltip: _hasLocalSshConfig ? 'SSH: $_sshHost (per-script override)' : 'Configure SSH connection for this script',
                onPressed: _openSshConnectionDialog,
              ),
              IconButton(icon: const Icon(Icons.close), onPressed: () => Navigator.of(context).pop(false)),
            ],
          ),
        ),
        const Divider(height: 1),
        // ── Body ──────────────────────────────────────────────
        Flexible(
          child: SingleChildScrollView(
            padding: const EdgeInsets.all(20),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                LayoutBuilder(
                  builder: (context, constraints) {
                    final isWide = constraints.maxWidth > 700;
                    final spacing = 12.0;
                    final timeoutWidth = 160.0;

                    final double nameWidth;
                    final double descWidth;
                    final double timeWidth;

                    if (isWide) {
                      final remaining = constraints.maxWidth - timeoutWidth - (spacing * 2);
                      nameWidth = (remaining / 3).floorToDouble();
                      descWidth = (nameWidth * 2).floorToDouble();
                      timeWidth = timeoutWidth;
                    } else {
                      nameWidth = constraints.maxWidth;
                      descWidth = constraints.maxWidth;
                      timeWidth = constraints.maxWidth;
                    }

                    final nameField = TextFormField(
                      controller: _nameCtrl,
                      decoration: InputDecoration(
                        labelText: L.of(context).scriptNameLabel,
                        hintText: L.of(context).scriptNameHint,
                        border: const OutlineInputBorder(),
                        prefixIcon: const Icon(Icons.label_outline),
                      ),
                    );

                    final descField = TextFormField(
                      controller: _descCtrl,
                      decoration: InputDecoration(
                        labelText: L.of(context).description,
                        hintText: L.of(context).scriptDescriptionHint,
                        border: const OutlineInputBorder(),
                        prefixIcon: const Icon(Icons.notes),
                      ),
                    );

                    final timeoutField = Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Expanded(
                          child: TextFormField(
                            controller: _timeoutCtrl,
                            keyboardType: TextInputType.number,
                            textAlign: TextAlign.center,
                            decoration: const InputDecoration(
                              labelText: 'Timeout',
                              border: OutlineInputBorder(),
                              contentPadding: EdgeInsets.symmetric(horizontal: 8, vertical: 10),
                              suffixText: 's',
                              prefixIcon: Icon(Icons.timer_outlined, size: 16),
                            ),
                            onChanged: (v) {
                              final parsed = int.tryParse(v);
                              if (parsed != null && parsed >= 5 && parsed <= 600) {
                                _timeoutSeconds = parsed;
                              }
                            },
                          ),
                        ),
                        const SizedBox(width: 4),
                        Column(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            IconButton(
                              icon: const Icon(Icons.keyboard_arrow_up, size: 18),
                              padding: EdgeInsets.zero,
                              constraints: const BoxConstraints(),
                              visualDensity: VisualDensity.compact,
                              onPressed: () {
                                setState(() {
                                  _timeoutSeconds = (_timeoutSeconds + 5).clamp(5, 600);
                                  _timeoutCtrl.text = _timeoutSeconds.toString();
                                });
                              },
                            ),
                            IconButton(
                              icon: const Icon(Icons.keyboard_arrow_down, size: 18),
                              padding: EdgeInsets.zero,
                              constraints: const BoxConstraints(),
                              visualDensity: VisualDensity.compact,
                              onPressed: () {
                                setState(() {
                                  _timeoutSeconds = (_timeoutSeconds - 5).clamp(5, 600);
                                  _timeoutCtrl.text = _timeoutSeconds.toString();
                                });
                              },
                            ),
                          ],
                        ),
                      ],
                    );

                    return Wrap(
                      spacing: spacing,
                      runSpacing: 12,
                      crossAxisAlignment: WrapCrossAlignment.center,
                      children: [
                        SizedBox(width: nameWidth, child: nameField),
                        SizedBox(width: descWidth, child: descField),
                        SizedBox(width: timeWidth, child: timeoutField),
                      ],
                    );
                  },
                ),
                if (_canUseLocalShellMode) ...[
                  const SizedBox(height: 8),
                  SwitchListTile.adaptive(
                    dense: true,
                    contentPadding: EdgeInsets.zero,
                    title: const Text('Run locally on this machine'),
                    subtitle: Text(
                      _runLocally ? 'Script runs locally (no SSH required).' : 'Script runs over SSH (global or per-script SSH settings).',
                      style: theme.textTheme.bodySmall,
                    ),
                    value: _runLocally,
                    onChanged: (v) => setState(() => _runLocally = v),
                  ),
                ],
                if (isServerMode) ...[
                  const SizedBox(height: 8),
                  Text(
                    'Server mode: scripts run through SSH. To target the host machine, configure SSH host as "localhost" (or host.docker.internal where supported).',
                    style: theme.textTheme.bodySmall?.copyWith(color: theme.colorScheme.onSurfaceVariant),
                  ),
                ],
                const SizedBox(height: 16),
                // ── LLM Generate strip ─────────────────────
                Card(
                  color: AppTheme.primaryBlue.withValues(alpha: 0.06),
                  child: Padding(
                    padding: const EdgeInsets.all(12),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Row(
                          children: [
                            Icon(Icons.auto_awesome, size: 16, color: AppTheme.primaryBlue),
                            const SizedBox(width: 8),
                            Text(
                              L.of(context).generateWithAiLabel,
                              style: theme.textTheme.labelLarge?.copyWith(color: AppTheme.primaryBlue),
                            ),
                          ],
                        ),
                        const SizedBox(height: 8),
                        TextField(
                          controller: _systemPromptCtrl,
                          minLines: 2,
                          maxLines: 4,
                          decoration: const InputDecoration(
                            labelText: 'Generation System Prompt',
                            hintText: 'Instructions for how the AI should generate this shell script.',
                            border: OutlineInputBorder(),
                            contentPadding: EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                          ),
                        ),
                        const SizedBox(height: 8),
                        Row(
                          children: [
                            Text('Generate with:', style: theme.textTheme.bodySmall?.copyWith(color: theme.colorScheme.onSurfaceVariant)),
                            const SizedBox(width: 8),
                            DropdownButton<String>(
                              value: _codeLlmChoice,
                              isDense: true,
                              underline: const SizedBox(),
                              items: [
                                DropdownMenuItem(value: 'llm1', child: Text('LLM 1 (Primary)')),
                                const DropdownMenuItem(value: 'llm2', child: Text('LLM 2 (Coding)')),
                              ],
                              onChanged: (v) => setState(() => _codeLlmChoice = v ?? 'llm1'),
                            ),
                          ],
                        ),
                        const SizedBox(height: 8),
                        LayoutBuilder(
                          builder: (context, constraints) {
                            final narrow = constraints.maxWidth < 520;
                            final inputField = TextField(
                              controller: _generatePromptCtrl,
                              minLines: 3,
                              maxLines: 6,
                              keyboardType: TextInputType.multiline,
                              decoration: InputDecoration(
                                hintText: L.of(context).generateScriptHint,
                                border: const OutlineInputBorder(),
                                contentPadding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                              ),
                            );

                            final generateButton = FilledButton.icon(
                              onPressed: !_generating && llmReady ? _generateScript : null,
                              icon: _generating
                                  ? const SizedBox(
                                      width: 16,
                                      height: 16,
                                      child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white),
                                    )
                                  : const Icon(Icons.send, size: 18),
                              label: Text(L.of(context).generateButton),
                              style: FilledButton.styleFrom(backgroundColor: AppTheme.primaryBlue),
                            );

                            if (narrow) {
                              return Column(
                                crossAxisAlignment: CrossAxisAlignment.stretch,
                                children: [
                                  inputField,
                                  const SizedBox(height: 8),
                                  Wrap(
                                    spacing: 8,
                                    runSpacing: 8,
                                    alignment: WrapAlignment.spaceBetween,
                                    crossAxisAlignment: WrapCrossAlignment.center,
                                    children: [
                                      _buildCommentsToggle(theme),
                                      SizedBox(height: 44, child: generateButton),
                                    ],
                                  ),
                                ],
                              );
                            }

                            return Row(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Expanded(child: inputField),
                                const SizedBox(width: 8),
                                _buildCommentsToggle(theme),
                                const SizedBox(width: 8),
                                SizedBox(height: 44, child: generateButton),
                              ],
                            );
                          },
                        ),
                        if (!llmReady) ...[
                          const SizedBox(height: 8),
                          Text(L.of(context).noLlmForScript, style: TextStyle(fontSize: 11, color: Colors.grey[600])),
                        ],
                      ],
                    ),
                  ),
                ),
                const SizedBox(height: 12),
                // Content label
                Text(L.of(context).scriptContentLabel, style: theme.textTheme.labelSmall?.copyWith(color: Colors.grey[600])),
                const SizedBox(height: 4),
                // Code editor
                CodeEditorField(controller: _contentCtrl, language: 'bash', title: L.of(context).scriptContentLabel, previewLines: 20),
                if (widget.onInsertScriptPrompt != null) ...[
                  const SizedBox(height: 12),
                  OutlinedButton.icon(
                    onPressed: () {
                      final name = _nameCtrl.text.trim();
                      if (name.isEmpty) {
                        ScaffoldMessenger.of(
                          context,
                        ).showSnackBar(SnackBar(content: Text(L.of(context).scriptNameRequiredMsg), backgroundColor: Colors.orange));
                        return;
                      }
                      widget.onInsertScriptPrompt?.call(name);
                      ScaffoldMessenger.of(
                        context,
                      ).showSnackBar(SnackBar(content: Text(L.of(context).insertedIntoPromptMsg), behavior: SnackBarBehavior.floating));
                      Navigator.of(context).pop(false);
                    },
                    icon: const Icon(Icons.add_circle_outline, size: 18),
                    label: Text(L.of(context).insertIntoPromptButton),
                  ),
                ],
              ],
            ),
          ),
        ),
        const Divider(height: 1),
        // ── Actions ───────────────────────────────────────────
        Padding(
          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.end,
            children: [
              TextButton(onPressed: () => Navigator.of(context).pop(false), child: Text(L.of(context).cancel)),
              const SizedBox(width: 6),
              OutlinedButton.icon(
                onPressed: (_testing || _generating || !_canTestRun) ? null : _testRun,
                icon: _testing
                    ? const SizedBox(width: 14, height: 14, child: CircularProgressIndicator(strokeWidth: 2))
                    : const Icon(Icons.play_arrow, size: 16),
                label: const Text('Test Run'),
                style: OutlinedButton.styleFrom(
                  padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                  tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                ),
              ),
              const SizedBox(width: 6),
              FilledButton.icon(
                onPressed: _saving ? null : _save,
                icon: _saving
                    ? const SizedBox(width: 16, height: 16, child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white))
                    : const Icon(Icons.save, size: 16),
                label: Text(isNew ? L.of(context).createScriptButton : L.of(context).save),
                style: FilledButton.styleFrom(
                  backgroundColor: AppTheme.primaryBlue,
                  padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                  tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                ),
              ),
            ],
          ),
        ),
      ],
    );

    return Dialog(
      insetPadding: isMobile ? EdgeInsets.zero : const EdgeInsets.symmetric(horizontal: 16, vertical: 24),
      clipBehavior: Clip.antiAlias,
      shape: isMobile ? const RoundedRectangleBorder() : null,
      child: SizedBox(
        width: isMobile ? screenSize.width : screenSize.width * 0.9,
        height: isMobile ? screenSize.height : screenSize.height * 0.9,
        child: SafeArea(
          child: dialogBody,
        ),
      ),
    );
  }

  Future<void> _openSshConnectionDialog() async {
    final ds = DataSourcesSettingsService.instance;
    if (!ds.isLoaded) await ds.load();
    if (!mounted) return;

    // Pre-fill with per-script override, or fall back to global settings
    final initHost = _sshHost.isNotEmpty ? _sshHost : ds.sshHost;
    final initPort = _sshHost.isNotEmpty ? _sshPort : ds.sshPort;
    final initUser = _sshUsername.isNotEmpty ? _sshUsername : ds.sshUsername;
    final initPass = _sshPassword.isNotEmpty ? _sshPassword : ds.sshPassword;

    final result = await showDialog<Map<String, dynamic>>(
      context: context,
      builder: (_) => _SshConnectionDialog(host: initHost, port: initPort, username: initUser, password: initPass),
    );

    if (result != null && mounted) {
      setState(() {
        _sshHost = result['host'] as String? ?? '';
        _sshPort = result['port'] as int? ?? 22;
        _sshUsername = result['username'] as String? ?? '';
        _sshPassword = result['password'] as String? ?? '';
      });
    }
  }
}

// ═══════════════════════════════════════════════════════════════
// Per-script SSH connection dialog
// ═══════════════════════════════════════════════════════════════

class _SshConnectionDialog extends StatefulWidget {
  final String host;
  final int port;
  final String username;
  final String password;

  const _SshConnectionDialog({required this.host, required this.port, required this.username, required this.password});

  @override
  State<_SshConnectionDialog> createState() => _SshConnectionDialogState();
}

class _SshConnectionDialogState extends State<_SshConnectionDialog> {
  late final TextEditingController _hostCtrl;
  late final TextEditingController _portCtrl;
  late final TextEditingController _usernameCtrl;
  late final TextEditingController _passwordCtrl;
  bool _obscurePassword = true;
  bool _testing = false;
  String? _testMessage;
  bool _testOk = false;

  @override
  void initState() {
    super.initState();
    _hostCtrl = TextEditingController(text: widget.host);
    _portCtrl = TextEditingController(text: widget.port > 0 ? widget.port.toString() : '22');
    _usernameCtrl = TextEditingController(text: widget.username);
    _passwordCtrl = TextEditingController(text: widget.password);
  }

  @override
  void dispose() {
    _hostCtrl.dispose();
    _portCtrl.dispose();
    _usernameCtrl.dispose();
    _passwordCtrl.dispose();
    super.dispose();
  }

  Future<void> _testConnection() async {
    setState(() {
      _testing = true;
      _testMessage = null;
    });
    final result = await SshMcpServer.testConnection(
      host: _hostCtrl.text.trim(),
      port: int.tryParse(_portCtrl.text.trim()) ?? 22,
      username: _usernameCtrl.text.trim(),
      password: _passwordCtrl.text.trim(),
    );
    if (!mounted) return;
    setState(() {
      _testing = false;
      _testOk = result['success'] == true;
      _testMessage = result['message'] as String?;
    });
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return AlertDialog(
      title: const Row(children: [Icon(Icons.dns, size: 20), SizedBox(width: 8), Text('SSH Connection')]),
      contentPadding: const EdgeInsets.fromLTRB(24, 16, 24, 0),
      content: SizedBox(
        width: 360,
        child: SingleChildScrollView(
          padding: EdgeInsets.only(bottom: MediaQuery.of(context).viewInsets.bottom),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Text(
                'Override SSH settings for this script. Leave empty to use global SSH settings.',
                style: theme.textTheme.bodySmall?.copyWith(color: theme.colorScheme.onSurfaceVariant),
              ),
              const SizedBox(height: 12),
              Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Expanded(
                    flex: 3,
                    child: TextField(
                      controller: _hostCtrl,
                      decoration: const InputDecoration(
                        labelText: 'Hostname / IP',
                        hintText: '192.168.1.10',
                        border: OutlineInputBorder(),
                        prefixIcon: Icon(Icons.dns, size: 18),
                        contentPadding: EdgeInsets.symmetric(horizontal: 10, vertical: 12),
                      ),
                    ),
                  ),
                  const SizedBox(width: 8),
                  SizedBox(
                    width: 72,
                    child: TextField(
                      controller: _portCtrl,
                      keyboardType: TextInputType.number,
                      decoration: const InputDecoration(
                        labelText: 'Port',
                        hintText: '22',
                        border: OutlineInputBorder(),
                        contentPadding: EdgeInsets.symmetric(horizontal: 10, vertical: 12),
                      ),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 10),
              TextField(
                controller: _usernameCtrl,
                decoration: const InputDecoration(
                  labelText: 'Username',
                  hintText: 'root',
                  border: OutlineInputBorder(),
                  prefixIcon: Icon(Icons.person, size: 18),
                  contentPadding: EdgeInsets.symmetric(horizontal: 10, vertical: 12),
                ),
              ),
              const SizedBox(height: 10),
              TextField(
                controller: _passwordCtrl,
                obscureText: _obscurePassword,
                decoration: InputDecoration(
                  labelText: 'Password',
                  border: const OutlineInputBorder(),
                  prefixIcon: const Icon(Icons.lock, size: 18),
                  contentPadding: const EdgeInsets.symmetric(horizontal: 10, vertical: 12),
                  suffixIcon: IconButton(
                    icon: Icon(_obscurePassword ? Icons.visibility_off : Icons.visibility, size: 18),
                    onPressed: () => setState(() => _obscurePassword = !_obscurePassword),
                  ),
                ),
              ),
              if (_testMessage != null) ...[
                const SizedBox(height: 8),
                Text(_testMessage!, style: TextStyle(fontSize: 12, color: _testOk ? AppTheme.success : AppTheme.error)),
              ],
              const SizedBox(height: 12),
              SizedBox(
                width: double.infinity,
                child: OutlinedButton.icon(
                  onPressed: _testing ? null : _testConnection,
                  icon: _testing
                      ? const SizedBox(width: 14, height: 14, child: CircularProgressIndicator(strokeWidth: 2))
                      : const Icon(Icons.network_check, size: 16),
                  label: const Text('Test Connection'),
                ),
              ),
            ],
          ),
        ),
      ),
      actionsPadding: const EdgeInsets.fromLTRB(16, 8, 16, 12),
      actions: [
        TextButton(onPressed: () => Navigator.pop(context), child: const Text('Cancel')),
        FilledButton(
          onPressed: () {
            Navigator.pop(context, {
              'host': _hostCtrl.text.trim(),
              'port': int.tryParse(_portCtrl.text.trim()) ?? 22,
              'username': _usernameCtrl.text.trim(),
              'password': _passwordCtrl.text.trim(),
            });
          },
          child: const Text('Apply'),
        ),
      ],
    );
  }
}

// ═══════════════════════════════════════════════════════════════
// Output box widget for test run results
// ═══════════════════════════════════════════════════════════════

class _OutputBox extends StatelessWidget {
  const _OutputBox({required this.text});
  final String text;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(10),
      decoration: BoxDecoration(
        color: Theme.of(context).brightness == Brightness.dark ? const Color(0xFF1E1E2E) : const Color(0xFFF5F5F5),
        borderRadius: BorderRadius.circular(6),
        border: Border.all(color: Theme.of(context).dividerColor),
      ),
      child: SelectableText(text, style: const TextStyle(fontFamily: 'monospace', fontSize: 12)),
    );
  }
}
